"""
Insights router — pre-computed insight retrieval endpoints.

Insights are generated by etl/insight_engine.py and stored in the insights table.
Available insight_types: underutilization, overload, disengagement_risk,
skill_underutilization, glue_person_identified.
"""

import uuid
from datetime import date

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy import text
from sqlalchemy.orm import Session

from app.dependencies import get_db, require_role
from schemas.insights import InsightOut

router = APIRouter()

_ROLES = ("admin", "org_analytics", "manager", "hrbp")


@router.get("/", response_model=list[InsightOut])
def list_insights(
    as_of: date,
    scope: str | None = None,
    scope_id: uuid.UUID | None = None,
    insight_type: str | None = None,
    severity: str | None = None,
    limit: int = 50,
    current_user: dict = require_role(*_ROLES),
    db: Session = Depends(get_db),
) -> list[InsightOut]:
    """List insights for a given snapshot date with optional filters.

    Results are ordered: high severity first, then by confidence descending.
    """
    filters = ["snapshot_date = :as_of", "is_active = true"]
    params: dict = {"as_of": as_of, "limit": limit}

    if scope is not None:
        filters.append("scope = :scope")
        params["scope"] = scope
    if scope_id is not None:
        filters.append("scope_id = :scope_id")
        params["scope_id"] = scope_id
    if insight_type is not None:
        filters.append("insight_type = :insight_type")
        params["insight_type"] = insight_type
    if severity is not None:
        filters.append("severity = :severity")
        params["severity"] = severity

    where = " AND ".join(filters)
    sql = text(f"""
        SELECT id, scope, scope_id, insight_type, snapshot_date,
               severity, title, insight_description, confidence, is_active
        FROM insights
        WHERE {where}
        ORDER BY
            CASE severity WHEN 'high' THEN 1 WHEN 'medium' THEN 2 ELSE 3 END,
            confidence DESC
        LIMIT :limit
    """)

    rows = db.execute(sql, params).mappings().all()
    return [InsightOut(**dict(r)) for r in rows]


@router.get("/{insight_id}", response_model=InsightOut)
def get_insight(
    insight_id: uuid.UUID,
    current_user: dict = require_role(*_ROLES),
    db: Session = Depends(get_db),
) -> InsightOut:
    """Retrieve a single insight by ID."""
    sql = text("""
        SELECT id, scope, scope_id, insight_type, snapshot_date,
               severity, title, insight_description, confidence, is_active
        FROM insights
        WHERE id = :insight_id
    """)
    row = db.execute(sql, {"insight_id": insight_id}).mappings().first()
    if row is None:
        raise HTTPException(status_code=404, detail="Insight not found")
    return InsightOut(**dict(row))
